language: java
sudo: false
jdk: oraclejdk8

before_install:
  - nvm install 6.9.5
  - node --version
  - npm install -g appium
  - npm install -g appium-doctor
  - npm install express
  - npm init
  - npm install --save-dev selenium-server-standalone-jar

script:
  - android list sdk --all

language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21
    
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - appium-doctor
  - adb devices
  - android list targets
  - cd Appium && mvn clean verify
  - ls
  - which java
  - cd target/classes
  - ls
  - set path=/usr/lib/jvm/java-8-oracle/bin/java
  - java -cp . lambo.SampleOne