language: java
sudo: false
jdk: oraclejdk8

before_install:
  - nvm install 6.9.5
  - node --version
  - npm init -f -y
  - npm install --save-dev selenium-server-standalone-jar

script:
  - cd Appium && mvn clean verify
  - ls
  - which java
  - cd target/classes
  - ls
  - set path=/usr/lib/jvm/java-8-oracle/bin/java
  - selenium
  - java -cp . lambo.SampleOne