language: java
sudo: false
jdk: oraclejdk8

before_install:
  - nvm install 6.9.5
  - node --version
  - npm install -g appium
  - ls

script:
  - appium-doctor
  - adb devices
  - android list targets
  - cd Appium/target/classes
  - ls
  - which java
  - set path=/usr/lib/jvm/java-8-oracle/bin/java
  - java -cp . lambo.SampleOne
  - appium